import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Navbar } from './components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={`${inter.className} bg-slate-50`} >
        <script src="../path/to/flowbite/dist/flowbite.min.js"></script>
        
        <Navbar/>

        <main className="max-w-screen-xl mx-auto p-4 ">
          {children}
        </main>
      </body>
    </html>
  )
}
