


GET http://127.0.0.1:8000/ HTTP/1.1
Content-Type: application/json

###
POST http://127.0.0.1:8000/jobs/  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE3MDA5OTY2NTF9.nnU-22oSxzQcJOznP5vRtoHgFKIf6EggniwJbehm9Pw
Content-Type: application/json

{
  "title":"3 accountant",
  "decription": "we are looking for somebody who is familiar with excel and math",
  "max_salary": 6000.0,
  "min_salary": 4500.0
}

###

DELETE  http://127.0.0.1:8000/jobs/5/  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE3MDA5OTY2NTF9.nnU-22oSxzQcJOznP5vRtoHgFKIf6EggniwJbehm9Pw
Content-Type: application/json


###

PUT http://127.0.0.1:8000/jobs/5/  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE3MDA5OTg2NTd9.YBctoSuHqwF3r-t6EtGdrZl2JW21UiBTum_is0iWgtQ
Content-Type: application/json

{
  "title":"12 accountants",
  "decription": "are you familiar with excel and math, get in touch",
  "max_salary": 6000.0,
  "min_salary": 5000.0
}
###

GET http://127.0.0.1:8000/users/  HTTP/1.1
Content-Type: application/json

###
POST http://127.0.0.1:8000/users HTTP/1.1
Content-Type: application/json

{
  "email": "spiderman@gmail.com",
  "password": "spiderman"
}

###
POST http://127.0.0.1:8000/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "spiderman@gmail.com",
  "password": "spiderman"
}


###
POST http://127.0.0.1:8000/users/profile HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE3MDA5ODc5Nzd9.G4iDzikzWNT1XYcpAjX78XhNQfNs_sGoc1tB8IvtWD4
Content-Type: application/json

{
  "first_name":"kareen",
  "last_name":"diop",
  "phone_number": "65 739 45 34",
  "address": "dakar",
  "resume":" this your boy kareem"
}

###
PUT  http://127.0.0.1:8000/users/profile/2  HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE3MDEwMDM5OTJ9.mRx49AmgosXjv1QLdT3NbI1_nbGXTyguMFcFCrAih-0
Content-Type: application/json

{
 "first_name": "nancy",
  "last_name": "kane",
  "phone_number": "77 739 48 56",
  "address": "dias",
  "resume": "this nancy."
}

###
GET http://127.0.0.1:8000/users/profile/2 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE3MDA5OTg2NTd9.YBctoSuHqwF3r-t6EtGdrZl2JW21UiBTum_is0iWgtQ
Content-Type: application/json